version: "2"

exclude_patterns:
  - "__tests__/"
  - "stories/"
  - "docs/"

plugins:
  tslint:
    enabled: true

checks:
  file-lines:
      config:
          threshold: 500
  method-lines:
      config:
        threshold: 100